version: '3'
services:
  db:
    image: postgres:9-alpine
    container_name: test-ejbca-db
    volumes:
      - ./test/var/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ejbca
      - POSTGRES_PASSWORD=ejbca

  ejbca:
    build: .
    links:
      - db
    container_name: test-ejbca
    environment:
      - EJBCA_DB_HOSTNAME=db
